#!/bin/bash

echo "🎯 ПОШАГОВАЯ ИНСТРУКЦИЯ ДЛЯ GOOGLE SEO"
echo "======================================"
echo ""
echo "📍 ШАГ 1: ДЕПЛОЙ И НАСТРОЙКА ДОМЕНА"
echo "-----------------------------------"
echo ""
echo "1.1 📁 Деплой проекта:"
echo "   • Vercel: git push → автоматический деплой"
echo "   • Netlify: drag&drop build папки"
echo "   • Любой хостинг с Node.js поддержкой"
echo ""
echo "1.2 🌐 Настройка домена:"
echo "   • Привяжи свой домен (например: autoad-broker.com)"
echo "   • Обнови .env в проде:"
echo "     NEXT_PUBLIC_BASE_URL=https://autoad-broker.com"
echo ""
echo "1.3 🔍 Проверь что работает:"
echo "   • https://autoad-broker.com/sitemap.xml"
echo "   • https://autoad-broker.com/robots.txt"
echo "   • https://autoad-broker.com/en"
echo "   • https://autoad-broker.com/uk"
echo "   • https://autoad-broker.com/ru"
echo ""
echo "📍 ШАГ 2: GOOGLE SEARCH CONSOLE"
echo "-------------------------------"
echo ""
echo "2.1 🔗 Открой: https://search.google.com/search-console"
echo ""
echo "2.2 ➕ Добавь домен:"
echo "   • Выбери 'URL prefix'"
echo "   • Введи: https://autoad-broker.com"
echo "   • Подтверди владение (HTML файл или DNS)"
echo ""
echo "2.3 🗺️ Добавь sitemap:"
echo "   • В меню слева: Sitemaps"
echo "   • Add new sitemap: sitemap.xml"
echo "   • Жми Submit"
echo ""
echo "📍 ШАГ 3: МОНИТОРИНГ И ОПТИМИЗАЦИЯ"
echo "----------------------------------"
echo ""
echo "3.1 📊 Создай Google Analytics:"
echo "   • https://analytics.google.com"
echo "   • Создай GA4 property"
echo "   • Скопируй Measurement ID (G-XXXXXXXXX)"
echo "   • Добавь в .env: NEXT_PUBLIC_GA_ID=G-XXXXXXXXX"
echo ""
echo "3.2 🔍 Проверь индексацию:"
echo "   • URL Inspection в Search Console"
echo "   • Введи каждый URL и жми 'Request indexing'"
echo "   • https://autoad-broker.com/en"
echo "   • https://autoad-broker.com/uk"
echo "   • https://autoad-broker.com/ru"
echo ""
echo "3.3 📱 Проверь в соцсетях:"
echo "   • Facebook Debugger: https://developers.facebook.com/tools/debug/"
echo "   • Twitter Card Validator: https://cards-dev.twitter.com/validator"
echo ""
echo "📍 ЧТО GOOGLE УВИДИТ АВТОМАТИЧЕСКИ:"
echo "===================================="
echo ""
echo "✅ SITEMAP.XML содержит:"
echo "   • Все 3 языковые версии"
echo "   • Правильные hreflang теги"
echo "   • Приоритеты и частота обновления"
echo ""
echo "✅ КАЖДАЯ СТРАНИЦА содержит:"
echo "   • Title и description на нужном языке"
echo "   • Open Graph для соцсетей"
echo "   • Canonical URL"
echo "   • Hreflang на другие языки"
echo "   • JSON-LD structured data"
echo ""
echo "✅ ROBOTS.TXT говорит:"
echo "   • Разрешено сканировать /en /uk /ru"
echo "   • Запрещено сканировать /api /_next"
echo "   • Где найти sitemap.xml"
echo ""
echo "🚨 НЕ ЗАБУДЬ ЗАМЕНИТЬ:"
echo "======================"
echo ""
echo "⚠️ ИКОНКИ В public/:"
echo "   • favicon.ico - 32x32px"
echo "   • apple-touch-icon.png - 180x180px"
echo "   • icon-192x192.png - для PWA"
echo "   • icon-512x512.png - для PWA"
echo "   • og-image.jpg - 1200x630px для соцсетей"
echo ""
echo "💡 РЕЗУЛЬТАТ:"
echo "=============="
echo ""
echo "После этих шагов Google:"
echo "   ✅ Найдет все 3 языковые версии"
echo "   ✅ Правильно поймет структуру сайта"
echo "   ✅ Будет показывать нужный язык в нужной стране"
echo "   ✅ Соцсети будут красиво показывать превью"
echo "   ✅ Поисковая выдача будет оптимальной"
echo ""
echo "🎉 ГОТОВО! Твой сайт будет идеально проиндексирован!"
